name: Deploy Go Service to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - nsc/go-service
    paths:
      - apps/go-html-to-md-service/**
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/go-html-to-md-service'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Set up Docker Buildx'
            uses: docker/setup-buildx-action@v3

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and Push Image'
            uses: docker/build-push-action@v6
            with:
              context: ./apps/go-html-to-md-service
              push: true
              tags: ghcr.io/firecrawl/go-html-to-md-service:latest
              cache-from: type=registry,ref=ghcr.io/firecrawl/go-html-to-md-service:buildcache
              cache-to: type=registry,ref=ghcr.io/firecrawl/go-html-to-md-service:buildcache,mode=max